language: java
addons:
    apt:
        packages:
            - swig
jdk:
    - oraclejdk8
before_install:
    - bash gdal_2.0.0_jni.sh
    - export LD_LIBRARY_PATH=RGISuite/lib:$HOME/gdal_2.0.0/lib:$HOME/gdal_2.0.0/swig/java
    - export GDAL_DATA=$HOME/gdal_2.0.0/share/gdal
    - export PATH=$PATH:RGISuite/lib:$HOME/gdal_2.0.0/lib
script:
    gradle test
after_success:
    - gradle cobertura coveralls
cache:
    directories:
        - $HOME/.m2
        - $HOME/gdal_2.0.0
