language: java
jdk:
    - oraclejdk8
before_install:
    - bash gdal_2.0.1_jni.sh
    - bash swig_1.3.40.sh
    - export LD_LIBRARY_PATH=RGISuite/lib:$HOME/gdal_2.0.1/lib:$HOME/gdal_2.0.1/swig/java
    - export GDAL_DATA=$HOME/gdal_2.0.1/share/gdal
    - export PATH=$HOME/swig-1.3.40:RGISuite/lib:$HOME/gdal_2.0.1/lib:$PATH
script:
    gradle test
after_success:
    - gradle cobertura coveralls
cache:
    directories:
        - $HOME/.m2
        - $HOME/gdal_2.0.1
        - $HOME/swig_1.3.40
