language: java
addons:
    apt:
        packages:
            - swig
            - tree
jdk:
    - oraclejdk8
before_install:
    - bash gdal_1.11.1_jni.sh
    - tree $HOME/gdal
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:RGISuite/lib
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/gdal/lib
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/gdal/swig/java
    - ls $HOME/gdal/data
    - export GDAL_DATA=$GDAL_DATA:$HOME/gdal/data
    - export PATH=$PATH:RGISuite/lib
    - export PATH=$PATH:$HOME/gdal/lib
install:
    - ./install-deps-linux.sh
    - mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
    - mvn test
after_success:
    - mvn clean cobertura:cobertura coveralls:report
cache:
    directories:
        - $HOME/.m2
        - $HOME/gdal
