language: java
jdk:
    - oraclejdk8
before_install:
    - sudo apt-get install gdal-bin
install:
    - ./install-deps-linux.sh
    - mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
    - mvn test
after_success:
    - mvn clean cobertura:cobertura coveralls:report
cache:
    directories:
        - $HOME/.m2
