language: java
jdk:
    - oraclejdk8
before_install:
    - bash gdal_1.11.1_jni.sh
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/gdal/lib/swig/java/
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/
    - export GDAL_DATA=$GDAL_DATA:/usr/local/share/gdal/
install:
    - ./install-deps-linux.sh
    - mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
    - mvn test
after_success:
    - mvn clean cobertura:cobertura coveralls:report
cache:
    directories:
        - $HOME/.m2
        - $HOME/gdal
