language: java
env:
  global:
   - secure: "WIAl49jT9jhp+1COTf7PAkn9SLsdKufzSqV5xDO4UiOHYpSJVunoPNWI2H/UdsWzznrHlQeZBpftrJ2ygZRMi0USt2mEUrA4V8s1teYKdxRUzWAzx2IePAwcwLVuAR/3/qYy7bpGeoyLHOsOw3dcP3A+gFdJaXeHeWh7bU02zG0="
jdk:
    - oraclejdk8
install:
    - export COVERALLS_SERVICE_NAME=travis-pro
    - export COVERALLS_REPO_TOKEN=D2hjjqELJcAAyA8sv1WgOZ1GENG27WXoR
    - ./install-deps-linux.sh
    - mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
    - mvn test
after_success:
    - mvn clean cobertura:cobertura coveralls:report
addons:
  coverity_scan:
    project:
      name: "GitHubRGI/swagd"
      description: "Build submitted via Travis CI"
    notification_email: build@rgi-corp.com
    build_command_prepend: "mvn clean"
    build_command:   "mvn -DskipTests=true compile"
    branch_pattern: coverity_scan
cache:
    directories:
        - $HOME/.m2
