language: java
env:
  global:
   - secure: "WIAl49jT9jhp+1COTf7PAkn9SLsdKufzSqV5xDO4UiOHYpSJVunoPNWI2H/UdsWzznrHlQeZBpftrJ2ygZRMi0USt2mEUrA4V8s1teYKdxRUzWAzx2IePAwcwLVuAR/3/qYy7bpGeoyLHOsOw3dcP3A+gFdJaXeHeWh7bU02zG0="
jdk:
    - oraclejdk8
install: mvn compile
script: mvn test
addons:
  coverity_scan:
    project:
      name: "GitHubRGI/swagd"
      description: "Build submitted via Travis CI"
    notification_email: build@rgi-corp.com
    build_command_prepend: "mvn clean"
    build_command:   "mvn -DskipTests=true package"
    branch_pattern: coverity_scan


